using System.Reflection;

namespace
{Title: 100 Things About me }
    internal class Program
    {
        static void Main(string[] args)
    { 
            Console.WriteLine("I was born in Fresno, California!");
            Console.WriteLine("I was raised in Hanford, California");
            Console.WriteLine("I am currently 20 years old");
            Console.WriteLine("I was born on September, 1st, 2005");
            Console.WriteLine("I am in my third year of college");
            Console.WriteLine("I am currently dual-majoring");
            Console.WriteLine("My first major is Business Administration");
            Console.WriteLine("My second major is Mechancial Engineering");
            Console.WriteLine("I want to get a Bachelor's degree in Mechanical Engineering");
            Console.WriteLine("I want to get my Associate's degree in Business Administration");
            Console.WriteLine("I go to school every Tuesday, Wednesday, and Thursday this semester");
            Console.WriteLine("My favorite hobby is Basketball");
            Console.WriteLine("I play Basketball almost always in my free time");
            Console.WriteLine("I play Basketball at least 4-5 times a week");
            Console.WriteLine("I play in Basketball leagues in both Lemoore and Lindsay");
            Console.WriteLine("I started playing in Basketball leagues when I was 15 years old");
            Console.WriteLine("I started playing in Basketball leagues during my junior year");
            Console.WriteLine("Basketball is my getaway from all the stresses in my life");
            Console.WriteLine("Basketball is my masseues, my ease away from life");
            Console.WriteLine("I have 5 Brothers");
            Console.WriteLine("I have 2 sisters");
            Console.WriteLine("Both of my sisters are older than me");
            Console.WriteLine("4 out of my 5 brothers are older than me");
            Console.WriteLine("I have 1 pet");
            Console.WriteLine("She is a dog");
            Console.WriteLine("Her name is Princess");
            Console.WriteLine("She is a Chihuahua");
            Console.WriteLine("There are four sports I enjoy watching a lot");
            Console.WriteLine("I watch Basketball");
            Console.WriteLine("I watch Football (or Soccer)");
            Console.WriteLine("I watch American Football");
            Console.WriteLine("I watch Baseball");
            Console.WriteLine("My favorite Basketball team is the Los Angeles Lakers");
            Console.WriteLine("My favorite Basketball player ever is Kobe Bryant");
            Console.WriteLine("My favorite American Football team is the Dallas Cowboys");
            Console.WriteLine("My favorite American Football player ever is Aaron Rodgers");
            Console.WriteLine("My favorite Baseball team is the Los Angeles Dodgers");
            Console.WriteLine("My favorite Baseball player ever is Barry Bonds");
            Console.WriteLine("My favorite Football team is Real Madrid");
            Console.WriteLine("My favorite Football player is Cristiano Ronaldo");
            Console.WriteLine("I believe Kobe Bryant is the Best & Greatest Basketball player ever");
            Console.WriteLine("I believe Kobe Bryant is also the greatest athlete ever");
            Console.WriteLine("I believe Tom Brady is the Greatest American Football player ever");
            Console.WriteLine("I believe Barry Bonds is the greatest Baseball player ever");
            Console.WriteLine("I believe Cristiano Ronaldo is the greatest Footballer ever");
            Console.WriteLine("My favorite subject used to be Physical Education");
            Console.WriteLine("My favorite subject became Math during my senior year of high school and has been my favorite ever since");
            Console.WriteLine("Math became my favorite subject because I realized how gifted and great I am at it");
            Console.WriteLine("I currently have a 3.92 GPA");
            Console.WriteLine("I've only gotten 2 B's throughout 3 years of College");
            Console.WriteLine("I have no experience with coding so I'm very nervous about this class");
            Console.WriteLine("My favorite artist is Lil Tjay");
            Console.WriteLine("Lil Tjay is my favorite artist because he is what really got me into music");
            Console.WriteLine("I believe Kanye West is the greatest artist ever (Sorry Michael Jackson fans, I have him second)");
            Console.WriteLine("I love buying shoes but I don't go overboard with it");
            Console.WriteLine("I believe in God");
            Console.WriteLine("I believe God walks with me every step of the way of my life");
            Console.WriteLine("I believe my future is very bright");
            Console.WriteLine("I realized how gifted and smart I was at a very young age");
            Console.WriteLine("I also realized how hard-working I am at a very young age");
            Console.WriteLine("Growing up, I motivated myself by telling myself that everything I do is for me");
            Console.WriteLine("That mentality worked until I hit my senior year of high school and the motivation wasn't enough for me and as a result, I was struggling in some of my classes");
            Console.WriteLine("I took Calculus during my senior year of high school");
            Console.WriteLine("I was in Honors Math classes throughout all of my four years of high school");
            Console.WriteLine("Once I hit college, I realized I needed a new motivation to continue working hard and that became my parents");
            Console.WriteLine("I motivate myself now by telling myself that everything I do is for my parents");
            Console.WriteLine("My dream is to make my mom and dad last years on Earth as happy as possible");
            Console.WriteLine("My favorite Snacks are Extra Hot Cheetos");
            Console.WriteLine("My favorite Candy is three Musketeers");
            Console.WriteLine("I am currently 5 feet 6 inches");
            Console.WriteLine("I currently weigh 130 pounds");
            Console.WriteLine("My favorite Drink is water");
            Console.WriteLine("My favorite music album is Yeezus by Kanye West");
            Console.WriteLine("My favorite song is Goat by Lil Tjay");
            Console.WriteLine("My dream universities are UC Berkeley and UC Irvine");
            Console.WriteLine("My family want me to go to UC Stanford because my uncle went there but I don't want to because the price is too high in my opinion");
            Console.WriteLine("My uncle graduated from UC Stanford with a Bachelor's degree in Mechanical Engineering");
            Console.WriteLine("I sometimes job shadow my uncle to get better insight on what Mechanical Engineers do");
            Console.WriteLine("My favorite YouTube channel currently is RDC");
            Console.WriteLine("I like to spend time with family & friends but not too much time");
            Console.WriteLine("I prefer spending more time by myself than with others as I love the peace and quiet I have by myself");
            Console.WriteLine("I also prefer spending time by myself than with others because I am introverted");
            Console.WriteLine("I've never had a girlfriend because I've always prioritized getting a career in Mechanical Engineeringbefore getting in a relationship");
            Console.WriteLine("I am not much of a traveling person but I would do it");
            Console.WriteLine("Not a lot of places interest me except France, which is my dream vacation");
            Console.WriteLine("My favorite fast-food place to eat is Angry Chicks");
            Console.WriteLine("My favorite restaurant is Applebees");
            Console.WriteLine("I like to also spend time and work on math homework, I look forward to it sometimes");
            Console.WriteLine("My favorite shoes are Kobe 6's");
            Console.WriteLine("I also play video games in my free-time");
            Console.WriteLine("I play on a Playstation 5");
            Console.WriteLine("I play a lot of Sports games and Roblox");
            Console.WriteLine("My favorite Video game ever is Teenage Mutant Ninja Turtles: Out of the Shadow");
            Console.WriteLine("My favorite game system is the GameCube");
            Console.WriteLine("My favorite color is Yellow");
            Console.WriteLine("My favorite number is 3");
            Console.WriteLine("Kobe Bryant is my idol because of his mentality and how hard-working he was at perfecting his craft in Basketball");
            Console.WriteLine("I have a bible next to my bed that I sleep in everyday");
            Console.WriteLine("My current shoe size is 11.5 in Men's");
            Console.WriteLine("I usually spend most of my time in the Library at school working on homework if I'm not in class");
        }
    }
}
